CREATE TABLE interface_schedule (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    interface_code    VARCHAR(100) NOT NULL UNIQUE,
    cron_expression   VARCHAR(100) NOT NULL,
    enabled           BOOLEAN      NOT NULL DEFAULT TRUE,
    payload_template  TEXT,
    created_at        TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at        TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_schedule_interface FOREIGN KEY (interface_code)
        REFERENCES interface_definition (interface_code)
);
